server.base-url=https://localhost:8443/secure-file-server-v2.0/files
ssl.trust-store=truststores/my_truststore
ssl.trust-store-password=Autumn2025
spring.main.web-application-type=none
#Here we set the timeout duration for handshake between the client and the server 
reactor.netty.tcp.sslHandshakeTimeout=20s