<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.7</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>springboot.examples</groupId>
	<artifactId>springboot.examples.ex33.client</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>SpringBoot Client</name>
	<description>SpringBoot client application</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- The following plugin is to make an executable jar file using spring boot -->
			<plugin>
				<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-maven-plugin -->
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
				<execution>
				<goals>
				<goal>repackage</goal>
				</goals>
				<configuration>
				<classifier>spring-boot</classifier>
				<mainClass>${main.class}</mainClass>
				</configuration>
				</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
				<execution>
				<phase>package</phase>
				<goals>
				<goal>single</goal>
				</goals>
				</execution>
				</executions>
				<configuration>
				<archive>
				<manifest>
				<addClasspath>true</addClasspath>
				<mainClass>${main.class}</mainClass>
				</manifest>
				</archive>
				<descriptorRefs>
				<descriptorRef>jar-with-dependencies</descriptorRef>
				</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
